### ISSUE TITLE
[BUG] Invalid produces very loud noise on ending

### ISSUE THREAD

**Issue by JonathanSchwartzHippo** [AhoyLemon/kinda.fun-old#109]
## The Game

Invalid

## The Bug

Me and some friends tried out the game and when we completed the game it produced an incredibly loud cacophony of noises.

## To Reproduce

I haven't been able to round them up to play the game since they are skittish of doing the noises again, so i haven't been able to test it again, but in theory reproduction should be just completing the game.

## Additional Context

This happened to everyone that completed the game, however one of the 7 players may have gotten disconnected at the end, which may have caused the issue since they apparently didn't wind up on the ending screen.

Browser wise, some of the players were using firefox and some were using chrome, all using windows.

**Comment by AhoyLemon** [comment]
Huh! That's interesting. Can you describe the noises? The very last noise should be this:

https://github.com/AhoyLemon/kinda.fun/blob/main/public/audio/invalid/crack-gong.mp3

**Comment by JonathanSchwartzHippo** [comment]
It was basically like it was playing that noise about 40000 times and clipping the audio insanely.

**Comment by AhoyLemon** [comment]
That's very weird. Was it at the game over screen? Or during the cracking round? I'm really stumped what would have caused that.
