### ISSUE TITLE
[ADD] Three Doctor Who actors

### ISSUE THREAD

**Issue by BiggerJ** [AhoyLemon/kinda.fun-old#111]
## The Game

Comparatively Famous

## Here's what I wanna add

Sylvester McCoy - The Seventh Doctor in Doctor Who - $100 - https://www.cameo.com/earthling7
Colin Baker - The Sixth Doctor in Doctor Who - $105 - https://www.cameo.com/colinbaker?qid=1616304476
Pearl Mackie - Bill Potts in Doctor Who - $50 - https://www.cameo.com/pearlmackie?qid=1616304625

**Comment by AhoyLemon** [comment]
Good lookin' out. I'll add 'em to the list. Thanks.
